apiVersion: v1
kind: Service
metadata:
  name: flask-frontend

spec:
  type: NodePort
  selector:
    app: flask-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32212
